### GET request to get all wineries
GET http://localhost:8080/wineries

### GET request to get winery by id
GET http://localhost:8080/wineries/2

### POST request to insert a new winery
POST http://localhost:8080/wineries
Content-Type: application/json

{
  "name": "Champagne Bollinger",
  "region": "Champagne",
  "address": "20 Boulevard Maréchal de Lattre, 51160, Aÿ"
}

### DELETE request to delete a winery by id
DELETE http://localhost:8080/wineries/2

### PUT request to update a winery
PUT http://localhost:8080/wineries/2
Content-Type: application/json

{
  "name": "Champagne Taittinger",
  "region": "Champagne",
  "address": "9 Place Saint-Nicaise, 51100 Reims"
}